name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm test

      # Upload coverage with retry and don't fail the build if upload fails
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        continue-on-error: false
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          flags: unittests
          fail_ci_if_error: false
          verbose: true
          # Add retries for rate limiting issues
        env:
          CODECOV_RETRY: 3
          CODECOV_RETRY_DELAY: 10
